FROM jupyter/minimal-notebook:latest

WORKDIR /home/jovyan
COPY . /home/jovyan

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 9999

# Tell Jupyter to listen on port 8888
CMD ["start-notebook.sh", "--NotebookApp.port=9999", "--NotebookApp.ip=0.0.0.0", \
     "--NotebookApp.open_browser=False", "--NotebookApp.allow_origin='*'"]
